### ISSUE TITLE
`date`  属性不要修改，目录顺序是根据它排序的！

### ISSUE THREAD

**Issue by justin-tang** [DiscoverMeteor/DiscoverMeteor_zh#11]
今天同步完之后发现目录顺序乱了，而且都是我翻译的那些...@_@（晕倒），估计可能是我昨天改了一下 `date` 那个属性...大家记得不要改那个属性！可能是根据那个来排序的，我现在改回来看看明天能不能恢复好...抱歉了~

**Comment by zhe** [comment]
Translation Guideline, No. 1 :smiley: 
- Do not modify the [YAML frontmatter](http://middlemanapp.com/basics/frontmatter/) at the top of each chapter, except for the `title` and `contents` fields.
