### ISSUE TITLE
申请加入翻译团队

### ISSUE THREAD

**Issue by zhe** [DiscoverMeteor/DiscoverMeteor_zh#45]
大家好 & @SachaG ,

本人看到有些章节还未翻译，进度才到 75%，现想申请加入团队来贡献一份力量，一起把如此优秀的书籍翻译更新至 1.0 版本。

zhe

**Comment by SachaG** [comment]
欢迎!

**Comment by zhe** [comment]
Thanks!

**Comment by kevingzhang** [comment]
Wow, Sacha, you can write Chinese ! Cool !!  (assuming you are not using
Google translate :)

**Comment by SachaG** [comment]
我会，中文是我的大学专业。但是我最近没有这么多机会联系…

**Comment by kevingzhang** [comment]
Amazing ! I did not know that. If I knew you can speak Chinese, I would talk with you last time I saw you in Meteor HQ in SF. 
Well, next time I will talk to you in Chinese when we meet :)

**Comment by SachaG** [comment]
Looking forward to it!
