### ISSUE TITLE
undefined is not a function  xl.js:266

### ISSUE THREAD

**Issue by l3ve** [DiscoverMeteor/DiscoverMeteor_zh#77]
例子本来没有的,但改着改着就出了这个错,找不到原因,求解释xl.js:266这个地方是干嘛用的

**Comment by zhe** [comment]
Hi I3ve, 虽然不知你在哪一步遇到这个问题，不过我建议你可以对比查看[本书 Microscope 在 GitHub 的源代码](https://github.com/DiscoverMeteor/Microscope)来找到你的问题答案。如果是书中代码有误，请指出。谢谢。

**Comment by kevingzhang** [comment]
Zhe
你在中国吗现在? 我刚刚从美国来中国出短差. 明天周日在北京的清华大学给很多 Meteor 爱好者讲解 Meteor. 如果你也在北京欢迎光临. 希望见见面.

**Comment by zhe** [comment]
@kevingzhang 遗憾我不在北京，这次不能向你当面请教了。很高兴有很多 Meteor 爱好者，记得分享视频呀。

**Comment by laosb** [comment]
@l3ve 不知道你是不是还在关注这里。xl.js是迅雷的Chrome插件的文件名，长期有这个错误存在，请忽视即可。
